sudo: enabled

language: csharp

solution: MilliSim.sln

env:
  - MAIN_VER=0.3.0 SOLUTION_NAME=MilliSim.sln CONFIGURATION=Release RELEASE_SUFFIX=-alpha

before_install:
  - sudo apt-get install -y gtk-sharp2 p7zip-full
  - sudo nvm install node --lts
  - sudo npm install -g npm
  - sudo npm install
  - sudo npm install -g marked

install:
  - node scripts/nuget_restore.js

before_script:
  - node scripts/patch_asminfo.js

script:
  # Disables "No doc for public member"
  - msbuild MilliSim.sln /p:Configuration=Release /verbosity:minimal /p:nowarn=1591

before_deploy:
  - marked ./README.md -o README.html
  - rm -f ${TRAVIS_BUILD_DIR}/OpenMLTD.MilliSim.Theater/bin/${CONFIGURATION}/*.xml
  - rm -f ${TRAVIS_BUILD_DIR}/OpenMLTD.MilliSim.Theater/bin/${CONFIGURATION}/*.pdb
  - 7z a millisim.zip -r ${TRAVIS_BUILD_DIR}/OpenMLTD.MilliSim.Theater/bin/${CONFIGURATION}/*
  - 7z a millisim.zip ${TRAVIS_BUILD_DIR}/README.html
  - cp millisim.zip millisim-travis-v${MAIN_VER}.${TRAVIS_BUILD_NUMBER}${RELEASE_SUFFIX}.zip
  - mv millisim.zip millisim-travis-latest.zip

#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:
#     secure: "TzHOHduzJDYF2xBvU7vMYLKfP0Vv/xkaLb5xr2otTRaeSzE+t/ePH9E3il/LBurcx3d4UYnqY8cz6mifcB3xV9Ktd5KXL6eIpJOoAMdKgEZune7+eN7F4Z3mPa3XuYfDy8NBeiSUxDnsKwVkb4VqJ+b4+Iz/2Pl87W5fd26TcuJCQPiuyPLJZl0s29wYLxyQzgKpakGAOwUs0IIiuZxFNddn6ZtCZKancAw2fXb8xlWLtEVyzCbTdmeyXTHXLkqYYdRbAeyEBOcrObzYi8x9SPRUsKNhNedUHIfyEUX2aeMiSpsptPcLlxOG0XHohuajfKGPQw8gxuxu4+K2H+HCSHgeTFEs/Hl490gUOHSUcTnSFEk8Eit1eQxd0i31Obd3yZsldkLD6fj1WygRil8RNwj+pyDU2nejoe28CiIF4R5kykUjFHIBnpYCOR815YWWuSjGGl1xR1CU26hZBOXEK6VGkwUe2EoNeGiR0rsSKzmED0exlKtqxqJSfWpsQHkF0GeHlCTDkcJTI4hOVcfv7LcwoDp4vlQMic++J0Pl5sI1lAUqvtgARmN3ESOjiztrxQ/5TwKtUC0SDW75HyLmly8QR00QPAg7aa6UMVTHM3sn0OHkdj8RwEArq/EZkEUfRrENsqaqC89/1Cc2dwuNpi0EuT6ajRGKeHwfrq9R9nc="
#  prerelease: true
#  file:
#    - millisim-travis-latest.zip
#    - millisim-travis-v${MAIN_VER}.${TRAVIS_BUILD_NUMBER}${RELEASE_SUFFIX}.zip
#  on:
#    tags: true
#    all_branches: true
#    condition: '${TRAVIS_TAG} != ""' # this is a tag push, not a commit push
