# @include <res/config/**/*.yml>

# Notes:
# 1. Please save this configuration file with UTF-8 encoding without BOM, codepage 65001.
# 2. Numeric values in 'layout' section can appear in 2 forms, integer (interpreted as pixels)
# or percentage (calculated based on window size).
# 3. MilliSim uses BGM time as the standard time. If BGM is not loaded, uses BGA instead. If neither is loaded, uses game time.
metadata:
  type: OpenMLTD.MilliSim.Theater.Configuration.MainAppConfig
  assembly_file: OpenMLTD.MilliSim.Theater.exe
  for: "@main"
  version: 1 # format version
data:
  window:
    width: 960 # width of the window's client area, in pixels
    height: 540 # height of the window's client area, in pixels
  plugins:
    loading:
      mode: default # default white_list, black_list
      lists:
        # ONLY plugins in white list will be loaded
        white_list: [ ]
        # All plugins in root and "plugins" directory EXCEPT those in black list will be loaded
        black_list: [ ]
          # file paths
          # - xxx.dll
    component_factories:
      # the latter, the closer to the top
      # core: base
      - plugin.component_factory.sync_timer
      - plugin.component_factory.audio_controller
      # core: visual backgrounds
      - plugin.component_factory.background_video
      - plugin.component_factory.background_image
      # score-related
      - plugin.component_factory.mltd_stage
      # ???
      - plugin.component_factory.cute_idol
      # overlays
      - plugin.component_factory.help_overlay
      - plugin.component_factory.fps_overlay
      - plugin.component_factory.debug_overlay
      - plugin.component_factory.sync_timer_overlay
      # ...
      #- plugin.component_factory.mini_cube
