# Notes:
# 1. Please save this configuration file with UTF-8 encoding without BOM, codepage 65001.
# 2. Numeric values in 'layout' section can appear in 2 forms, integer (interpreted as pixels)
# or percentage (calculated based on window size).

metadata:
  version: 1 # format version
game:
  difficulty: mm # 2m, 2m+, 4m, 6m, mm; number of tracks is set accordingly
  title: "Blue Symphony"
  scoreobj: game/scrobj_blsymp.unity3d # .unity3d (raw format from MLTD), .json
media:
  bgm: game/song3_blsymp_bgm.ogg # path to background music (BGM)
  #bga: media/bga.mp4 # path to background animation (BGA), a video
  #bga: F:\Independent Software\JiJiDown\Download\1.偶像大师MLTD手游Shooting Stars MM难度FC-1.1(Av13332401,P1).flv-muxed.mp4
  #bga: F:\Independent Software\JiJiDown\Download\4.【ミリシタMLTD】偶像大师百万现场Theater Days初始曲目Million Mix难度谱面-4.Blue Symphony(Av11726668,P4).mp4
  #bgi: D:\Pictures\912721fae6cd7b8930e4d2db0e2442a7d8330efa.jpg.png # path to background image (BGI)
  # Note: if BGA and BGI are both set, BGA will be used.
  bgm_volume: 100% # volume of BGM (0% - 100%)
  bga_volume: 0% # volume of BGA (0% - 100%)
  sfx_volume: 100% # volume of sound effects (0% - 100%)
window:
  orientation: landscape # "landscape" or "portrait"
  width: 960 # width of the window's client area, in pixels
  height: 540 # height of the window's client area, in pixels
  fonts:
    ui: res/fonts/MSYH.TTC
    song_title: res/fonts/MSYH.TTC
style:
  sync_line: yes # true, yes, y, on, 1
  flick_ribbon: no # false, no, n, off, 0
  slide_middle_sync_line: no
system_ui:
  debug_overlay:
    use: yes # displays debug info overlay
    font_size: 15
    text_fill: '#ffff00'
    # text_stroke: # (ignored)
  fps_overlay:
    use: yes # displays FPS overlay
    font_size: 15
    text_fill: '#ffff'
images:
  tap_point:
    file: res/images/ui/tap_point.png # 128x128
    blank_edge:
      left: 14
      top: 14
      right: 14
      bottom: 14
  tap_bar_chain:
    file: res/images/ui/tap_bar_chain.png # 32x32
  tap_bar_node:
    file: res/images/ui/tap_bar_node.png # 74x74
  hp_gauge:
    base:
      file: res/images/ui/hp_gauge_base.png
    progress:
      file: res/images/ui/hp_gauge_progress.png
  avatars:
    mask:
      file: res/images/ui/avatars_mask.png
    icons:
      - file: res/images/avatars/1.png
      - file: res/images/avatars/2.png
      - file: res/images/avatars/3.png
      - file: res/images/avatars/4.png
      - file: res/images/avatars/5.png
  score_rank:
    base:
      file: res/images/ui/score_rank.png
    icons:
      file: res/images/ui/score_rank_icons.png
  combo_counter:
    file: res/images/ui/combo_counter.png
  full_combo:
    file: res/images/ui/full_combo.png
    count: 10
  live_clear:
    file: res/images/ui/live_clear.png
    count: 10
  score_numbers:
    file: res/images/numbers/score.png # 0-9
  combo_numbers:
    file: res/images/numbers/combo.png # 0-9
  hit_rank:
    file: res/images/ui/hit_rank.png # perfect, great, good, fast, slow, miss; left to right
    count: 10 # top to bottom
  notes: # notes: tap (small, large), hold (small, large), flick (left, up, right), slide (start, middle, end)
    - file: res/images/notes/default.png # style=0 (default notes set), 160x160
      count: 10
      orientation: horizontal
    #- file: res/images/notes/style1.png # style=1
    #  count: 10
    #- file: res/images/notes/style2.png # style=2
    #  count: 10
  special_note:
    file: res/images/notes/special_note.png # 384x384
  ribbon:
    file: res/images/ui/ribbon.png # 128x128
  sync_line:
    file: res/images/sync_line.png
  difficulty_badges:
    file: res/images/difficulty_badges.png
    count: 6
localization:
  press_space_to_start: Press space key to play #スペースで再生
scaling:
  base: 960x540
  tap_point: 114x114
  tap_bar_chain: 4x4
  tap_bar_node: 16x16
  note:
    start: 20x20
    end: 120x120
  special_note:
    start: 200x200
    end: 280x280
  sync_line: 5x0
  ribbon: 20x0
ui:
  tap_points:
    layout:
      x: 50% # x position (anchor: center)
      y: 83% # y position (anchor: middle)
      width: 61% # width (from center of left-most point, to center of right-most point)
    opacity: 80%
  hp_gauge:
    layout:
      x: 5% # x position (anchor: left)
      y: 5% # y position (anchor: top)
  avatars:
    layout:
      x: 5% # x position (anchor: left)
      y: 10% # y position (anchor: top)
  score_rank:
    layout:
      x: 80% # x position (anchor: left)
      y: 10% # y position (anchor: top)
  combo_counter:
    layout:
      x: 80% # x position (anchor: left)
      y: 20% # y position (anchor: top)
  notes_layer:
    layout:
      y: 15% # (anchor: top)
    opacity: 80%
  ribbons_layer:
    opacity: 80%
  title:
    layout:
      x: 5% # x position (anchor: left)
      y: 30% # y position (anchor: top)
  hit_rank:
    layout:
      x: 50% # x position (anchor: center)
      y: 70% # y position (anchor: middle)
sfx: # sound effect files
  tap:
    perfect:
    great:
    nice:
    bad:
    miss:
  hold:
    perfect:
    great:
    nice:
    bad:
    miss:
  flick:
    perfect:
    great:
    nice:
    bad:
    miss:
  slide:
    perfect:
    great:
    nice:
    bad:
    miss:  
