## @include audio_manager/*.yml
metadata:
  type: OpenMLTD.MilliSim.Extension.Components.CoreComponents.Configuration.AudioControllerConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.CoreComponents.dll
  for: component.core.audio_controller
  version: 1 # format version
data:
  bgm: game/song3_shtstr_bgm.ogg # path to background music (BGM)
  bgm_volume: 100% # volume of BGM (0% - 100%)
  sfx_volume: 100% # volume of sound effects (0% - 100%)
  sfx: # sound effect files; format: 44100 Hz, 16-bit integer, 2 channels
    tap:
      perfect: res/sfx/rhy_tap.wav
      great: res/sfx/app_great.wav
      nice: res/sfx/app_good.wav
      bad: res/sfx/app_fast.wav
      miss: res/sfx/app_miss.wav
    hold:
      perfect: res/sfx/rhy_tap.wav
      great: res/sfx/app_great.wav
      nice: res/sfx/app_good.wav
      bad: res/sfx/app_fast.wav
      miss: res/sfx/app_miss.wav
    flick:
      perfect: res/sfx/app_flick.wav
      great: res/sfx/app_great.wav
      nice: res/sfx/app_good.wav
      bad: res/sfx/app_fast.wav
      miss: res/sfx/app_miss.wav
    slide:
      perfect: res/sfx/rhy_tap.wav
      great: res/sfx/app_great.wav
      nice: res/sfx/app_good.wav
      bad: res/sfx/app_fast.wav
      miss: res/sfx/app_miss.wav
    slide_hold: res/sfx/app_hold_up.wav
    hold_hold: res/sfx/app_hold.wav
    slide_end:
      perfect: res/sfx/app_hold_rub.wav
      great: res/sfx/app_great.wav
      nice: res/sfx/app_good.wav
      bad: res/sfx/app_fast.wav
      miss: res/sfx/app_miss.wav
    hold_end:
      perfect: res/sfx/app_hold_end.wav
      great: res/sfx/app_great.wav
      nice: res/sfx/app_good.wav
      bad: res/sfx/app_fast.wav
      miss: res/sfx/app_miss.wav
    special:
      perfect: res/sfx/app_special.wav
      great: res/sfx/app_great.wav
      nice: res/sfx/app_good.wav
      bad: res/sfx/app_fast.wav
      miss: res/sfx/app_miss.wav
    special_end: res/sfx/app_special_end.wav
    special_hold: res/sfx/app_special_loop.wav
    shouts: # around 3 seconds
      #- res/sfx/shout01.wav
      #- res/sfx/shout02.wav
      - res/sfx/shout03.wav
